-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 17:16:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema winterExercise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema winterExercise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `winterExercise` DEFAULT CHARACTER SET utf8 ;
USE `winterExercise` ;

-- -----------------------------------------------------
-- Table `winterExercise`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`users` (
                                                        `userId` VARCHAR(20) NOT NULL,
                                                        `userPw` VARCHAR(100) NOT NULL,
                                                        `userNm` VARCHAR(20) NOT NULL,
                                                        `userNick` VARCHAR(20) NOT NULL,
                                                        `grade` VARCHAR(20) NOT NULL,
                                                        PRIMARY KEY (`userId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`addr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`addr` (
                                                       `addrSeq` INT NOT NULL AUTO_INCREMENT,
                                                       `addrShip` VARCHAR(5) NOT NULL,
                                                       `addrBasic` VARCHAR(100) NOT NULL,
                                                       `addrDetail` VARCHAR(100) NOT NULL,
                                                       `userId` VARCHAR(20) NOT NULL,
                                                       INDEX `fk_addr_users_idx` (`userId` ASC),
                                                       PRIMARY KEY (`addrSeq`),
                                                       CONSTRAINT `fk_addr_users`
                                                           FOREIGN KEY (`userId`)
                                                               REFERENCES `winterExercise`.`users` (`userId`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB
    COMMENT = '			';


-- -----------------------------------------------------
-- Table `winterExercise`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`orders` (
                                                         `orderSeq` INT NOT NULL AUTO_INCREMENT,
                                                         `userId` VARCHAR(20) NOT NULL,
                                                         `orderAddr` VARCHAR(45) NOT NULL,
                                                         `orderPhone` VARCHAR(45) NOT NULL,
                                                         `orderCommentBoss` VARCHAR(45) NOT NULL,
                                                         `orderCommentRider` VARCHAR(45) NOT NULL,
                                                         `orderAmount` VARCHAR(45) NOT NULL,
                                                         `orderWay` VARCHAR(45) NOT NULL,
                                                         `deliveryYN` VARCHAR(45) NOT NULL,
                                                         `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                         PRIMARY KEY (`orderSeq`),
                                                         INDEX `fk_orders_users1_idx` (`userId` ASC),
                                                         CONSTRAINT `fk_orders_users1`
                                                             FOREIGN KEY (`userId`)
                                                                 REFERENCES `winterExercise`.`users` (`userId`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`category` (
                                                           `categorySeq` INT NOT NULL AUTO_INCREMENT,
                                                           `categoryNm` VARCHAR(45) NOT NULL,
                                                           PRIMARY KEY (`categorySeq`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`stores` (
                                                         `storeSeq` INT NOT NULL AUTO_INCREMENT,
                                                         `categorySeq` INT NOT NULL,
                                                         `storeTitle` VARCHAR(45) NOT NULL,
                                                         `mimAmount` VARCHAR(45) NOT NULL,
                                                         `payMethod` VARCHAR(45) NOT NULL,
                                                         `deliveryTime` VARCHAR(45) NOT NULL,
                                                         `deliveryTip` VARCHAR(45) NOT NULL,
                                                         `image` VARCHAR(100) NOT NULL,
                                                         PRIMARY KEY (`storeSeq`),
                                                         INDEX `fk_stores_category1_idx` (`categorySeq` ASC),
                                                         CONSTRAINT `fk_stores_category1`
                                                             FOREIGN KEY (`categorySeq`)
                                                                 REFERENCES `winterExercise`.`category` (`categorySeq`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`menuGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`menuGroup` (
                                                            `menuGroupSeq` INT NOT NULL AUTO_INCREMENT,
                                                            `storeSeq` INT NOT NULL,
                                                            `groupNm` VARCHAR(45) NOT NULL,
                                                            `groupExplain` VARCHAR(45) NULL,
                                                            PRIMARY KEY (`menuGroupSeq`),
                                                            INDEX `fk_menuGroup_stores1_idx` (`storeSeq` ASC),
                                                            CONSTRAINT `fk_menuGroup_stores1`
                                                                FOREIGN KEY (`storeSeq`)
                                                                    REFERENCES `winterExercise`.`stores` (`storeSeq`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`menu` (
                                                       `menuSeq` INT NOT NULL AUTO_INCREMENT,
                                                       `menuGroupSeq` INT NOT NULL,
                                                       `menuTitle` VARCHAR(45) NOT NULL,
                                                       `menuSub` VARCHAR(45) NOT NULL,
                                                       `menuPrice` VARCHAR(45) NOT NULL,
                                                       PRIMARY KEY (`menuSeq`),
                                                       INDEX `fk_menu_menuGroup1_idx` (`menuGroupSeq` ASC),
                                                       CONSTRAINT `fk_menu_menuGroup1`
                                                           FOREIGN KEY (`menuGroupSeq`)
                                                               REFERENCES `winterExercise`.`menuGroup` (`menuGroupSeq`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`orderMenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`orderMenu` (
                                                            `orderMenuSeq` INT NOT NULL AUTO_INCREMENT,
                                                            `orderSeq` INT NOT NULL,
                                                            `menuSeq` INT NOT NULL,
                                                            `orderCount` INT NOT NULL,
                                                            PRIMARY KEY (`orderMenuSeq`),
                                                            INDEX `fk_orderMenu_orders1_idx` (`orderSeq` ASC),
                                                            INDEX `fk_orderMenu_menu1_idx` (`menuSeq` ASC),
                                                            CONSTRAINT `fk_orderMenu_orders1`
                                                                FOREIGN KEY (`orderSeq`)
                                                                    REFERENCES `winterExercise`.`orders` (`orderSeq`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION,
                                                            CONSTRAINT `fk_orderMenu_menu1`
                                                                FOREIGN KEY (`menuSeq`)
                                                                    REFERENCES `winterExercise`.`menu` (`menuSeq`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `winterExercise`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `winterExercise`.`review` (
                                                         `reviewSeq` INT NOT NULL AUTO_INCREMENT,
                                                         `orderSeq` INT NOT NULL,
                                                         `rating` INT NOT NULL,
                                                         `comment` VARCHAR(45) NOT NULL,
                                                         `createAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                         PRIMARY KEY (`reviewSeq`),
                                                         INDEX `fk_review_orders1_idx` (`orderSeq` ASC),
                                                         CONSTRAINT `fk_review_orders1`
                                                             FOREIGN KEY (`orderSeq`)
                                                                 REFERENCES `winterExercise`.`orders` (`orderSeq`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
